branches:
  # whitelist
  only:
    - master

# scripts that are called at very beginning, before repo cloning
init:
    git config --system core.longpaths true


# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  parallel: true                    # enable MSBuild parallel builds
  project: WebSite\WebTool.sln      # path to Visual Studio solution or project
  publish_wap: true

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node 4.2.4
  # install modules

  # Install Gulp
  #- Setup.bat

  - copy "WebSite\WebTool\Web.template.config" "WebSite\WebTool\Web.config"

  # Install Gulp
  - npm install -g gulp

  # Install Dependencies
  - npm install --prefix WebSite



#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:

