branches:
  # whitelist
  only:
    - master

# scripts that are called at very beginning, before repo cloning
init:
    git config --system core.longpaths true


# build Configuration, i.e. Debug, Release, etc.
configuration: Debug


services:
  - mssql2008r2sp2      # start sql server 2008
  - iis                 # start IIS

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node 4.2.4
  # install modules

  # Install Gulp
  #- Setup.bat

  - copy "WebSite\WebTool\Web.template.config" "WebSite\WebTool\Web.config"

  # Install Gulp
  - npm install -g gulp

  # Install Dependencies
  - npm install --prefix WebSite


# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  parallel: true                    # enable MSBuild parallel builds
  project: WebSite\WebTool.sln      # path to Visual Studio solution or project
  publish_wap: true


# scripts to run after build
after_build:
  # Attach the Database
  - ps: .\appveyor-attachdb-sql.ps1

  # Create the iis website
  - ps: .\CreateIISWebSite.ps1

  # Enable SQL Server name pipe and TCP-IP
  - ps: .\sql-server-ip-and-alias.ps1

  # Test The Database
  - sqlcmd -S "(local)\SQL2008R2SP2" -U "sa" -P "Password12!" -Q "SELECT * FROM information_schema.tables;" -d "master"
  - sqlcmd -S "(local)\SQL2008R2SP2" -U "sa" -P "Password12!" -Q "SELECT * FROM dbo.Users;" -d "WebTool"

  # Test IIS
  - WebSite\Test\BDD\phantomjs.exe WebSite\Test\BDD\phantomjs_Debug.js

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - 'WebSite\Test\BDD\bin\Debug\BDD.dll'
