branches:
  # whitelist
  only:
    - master

# scripts that are called at very beginning, before repo cloning
init:
    git config --system core.longpaths true


# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  parallel: true                    # enable MSBuild parallel builds
  project: WebSite\WebTool.sln      # path to Visual Studio solution or project


install:
  # Get the latest stable version of Node.js or io.js
  #- ps: Install-Product node
  # install modules

  # Install Gulp
  - npm install -g gulp

  # Install Dependencies
  - cd WebSite
  - npm install gulp-typescript
  - cd ..