branches:
  # whitelist
  only:
    - master

# scripts that are called at very beginning, before repo cloning
init:
    git config --system core.longpaths true


# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  parallel: true                    # enable MSBuild parallel builds
  project: WebSite\WebTool.sln      # path to Visual Studio solution or project
  publish_wap: true

services:
  - mssql2008r2sp2      # start SQL Server 2008 R2 SP2 Express
  - iis

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node 4.2.4
  # install modules

  # Install Gulp
  #- Setup.bat

  - copy "WebSite\WebTool\Web.template.config" "WebSite\WebTool\Web.config"

  # Install Gulp
  - npm install -g gulp

  # Install Dependencies
  - npm install --prefix WebSite

  # Attach the Database
  - ps: appveyor-attachdb-sql.ps1

  # Create the iis website
  - ps: CreateIISWebSite.ps1

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:

