//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolCulture.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebToolCulture.Resource.UIResource", typeof(UIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha.
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha is not valid..
        /// </summary>
        public static string Captchaisnotvalid {
            get {
                return ResourceManager.GetString("Captchaisnotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is required!.
        /// </summary>
        public static string ConfirmPasswordIsRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        public static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have a account?.
        /// </summary>
        public static string DontHaveAAccount {
            get {
                return ResourceManager.GetString("DontHaveAAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name.
        /// </summary>
        public static string HostName {
            get {
                return ResourceManager.GetString("HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there a typo in the url?.
        /// </summary>
        public static string Isthereatypointheurl {
            get {
                return ResourceManager.GetString("Isthereatypointheurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your account.
        /// </summary>
        public static string LoginToYourAccount {
            get {
                return ResourceManager.GetString("LoginToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Address.
        /// </summary>
        public static string MACAddress {
            get {
                return ResourceManager.GetString("MACAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opps, Something went wrong..
        /// </summary>
        public static string OppsSomethingwentwrong {
            get {
                return ResourceManager.GetString("OppsSomethingwentwrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opps, You&apos;re lost..
        /// </summary>
        public static string OppsYourelost {
            get {
                return ResourceManager.GetString("OppsYourelost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Page.
        /// </summary>
        public static string Page404 {
            get {
                return ResourceManager.GetString("Page404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 Page.
        /// </summary>
        public static string Page500 {
            get {
                return ResourceManager.GetString("Page500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Paging_of {
            get {
                return ResourceManager.GetString("Paging_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be longer than 20 characters!.
        /// </summary>
        public static string PasswordCannotBeLongerThan20Characters {
            get {
                return ResourceManager.GetString("PasswordCannotBeLongerThan20Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required!.
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please come back in a while..
        /// </summary>
        public static string Pleasecomebackinawhile {
            get {
                return ResourceManager.GetString("Pleasecomebackinawhile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record(s).
        /// </summary>
        public static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records per page.
        /// </summary>
        public static string RecordsPerPage {
            get {
                return ResourceManager.GetString("RecordsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up now.
        /// </summary>
        public static string SignUpNow {
            get {
                return ResourceManager.GetString("SignUpNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statistics and more.
        /// </summary>
        public static string StatisticsAndMore {
            get {
                return ResourceManager.GetString("StatisticsAndMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subnet Mask.
        /// </summary>
        public static string SubnetMask {
            get {
                return ResourceManager.GetString("SubnetMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match!.
        /// </summary>
        public static string ThePasswordAndConfirmationPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("ThePasswordAndConfirmationPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exist!.
        /// </summary>
        public static string UserAlreadyExist {
            get {
                return ResourceManager.GetString("UserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name cannot be longer than 10 characters!.
        /// </summary>
        public static string UserNameCannotBeLongerThan10Characters {
            get {
                return ResourceManager.GetString("UserNameCannotBeLongerThan10Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required!.
        /// </summary>
        public static string UserNameIsRequired {
            get {
                return ResourceManager.GetString("UserNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name or password error!.
        /// </summary>
        public static string UserNameOrPasswordError {
            get {
                return ResourceManager.GetString("UserNameOrPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wake On Lan.
        /// </summary>
        public static string WakeOnLan {
            get {
                return ResourceManager.GetString("WakeOnLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wake Up.
        /// </summary>
        public static string WakeUp {
            get {
                return ResourceManager.GetString("WakeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are fixing it!.
        /// </summary>
        public static string Wearefixingit {
            get {
                return ResourceManager.GetString("Wearefixingit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Tool.
        /// </summary>
        public static string WebTool {
            get {
                return ResourceManager.GetString("WebTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can not find the page you&apos;re looking for..
        /// </summary>
        public static string Wecannotfindthepageyourelookingfor {
            get {
                return ResourceManager.GetString("Wecannotfindthepageyourelookingfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WOL.
        /// </summary>
        public static string WOL {
            get {
                return ResourceManager.GetString("WOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WOL List.
        /// </summary>
        public static string WOLList {
            get {
                return ResourceManager.GetString("WOLList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string WOLName {
            get {
                return ResourceManager.GetString("WOLName", resourceCulture);
            }
        }
    }
}
