//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOL
    {
        public int WOLID { get; set; }
        public int UserId { get; set; }
        public string WOLName { get; set; }
        public string MACAddress { get; set; }
        public string SubnetMask { get; set; }
        public string HostName { get; set; }
        public Nullable<int> Port { get; set; }
        public string Protocol { get; set; }
    
        public virtual User User { get; set; }
    }
}
